resources:
- ../base
- env-ops-configmap.yaml
- rc3e5632/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: rc3e5632/revision-patch.yaml
  target:
    kind: Service
- path: rc3e5632/routing-patch.yaml
  target:
    kind: Service