resources:
- ../base
- env-ops-configmap.yaml
- r6b4d03a/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r6b4d03a/revision-patch.yaml
  target:
    kind: Service
- path: r6b4d03a/routing-patch.yaml
  target:
    kind: Service