resources:
- ../base
- env-ops-configmap.yaml
- r3cefe0b/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r3cefe0b/revision-patch.yaml
  target:
    kind: Service
- path: r3cefe0b/routing-patch.yaml
  target:
    kind: Service