resources:
- ../base
- env-ops-configmap.yaml
- r7fcf64a/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r7fcf64a/revision-patch.yaml
  target:
    kind: Service
- path: r7fcf64a/routing-patch.yaml
  target:
    kind: Service