resources:
- ../base
- env-ops-configmap.yaml
- r507012e/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r507012e/revision-patch.yaml
  target:
    kind: Service
- path: r507012e/routing-patch.yaml
  target:
    kind: Service