resources:
- ../base
- env-ops-configmap.yaml
- rb30cb68/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: rb30cb68/revision-patch.yaml
  target:
    kind: Service
- path: rb30cb68/routing-patch.yaml
  target:
    kind: Service